/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as publicRouteRouteImport } from './routes/(public)/route'
import { Route as protectedRouteRouteImport } from './routes/(protected)/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as publicOnboardingRouteImport } from './routes/(public)/onboarding'
import { Route as protectedTransactionsRouteImport } from './routes/(protected)/transactions'
import { Route as protectedSyncRouteImport } from './routes/(protected)/sync'
import { Route as protectedSettingsRouteImport } from './routes/(protected)/settings'
import { Route as protectedReportsRouteImport } from './routes/(protected)/reports'
import { Route as protectedLedgersRouteImport } from './routes/(protected)/ledgers'
import { Route as protectedDashboardRouteImport } from './routes/(protected)/dashboard'
import { Route as protectedBudgetsRouteImport } from './routes/(protected)/budgets'

const publicRouteRoute = publicRouteRouteImport.update({
  id: '/(public)',
  getParentRoute: () => rootRouteImport,
} as any)
const protectedRouteRoute = protectedRouteRouteImport.update({
  id: '/(protected)',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const publicOnboardingRoute = publicOnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => publicRouteRoute,
} as any)
const protectedTransactionsRoute = protectedTransactionsRouteImport.update({
  id: '/transactions',
  path: '/transactions',
  getParentRoute: () => protectedRouteRoute,
} as any)
const protectedSyncRoute = protectedSyncRouteImport.update({
  id: '/sync',
  path: '/sync',
  getParentRoute: () => protectedRouteRoute,
} as any)
const protectedSettingsRoute = protectedSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => protectedRouteRoute,
} as any)
const protectedReportsRoute = protectedReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => protectedRouteRoute,
} as any)
const protectedLedgersRoute = protectedLedgersRouteImport.update({
  id: '/ledgers',
  path: '/ledgers',
  getParentRoute: () => protectedRouteRoute,
} as any)
const protectedDashboardRoute = protectedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => protectedRouteRoute,
} as any)
const protectedBudgetsRoute = protectedBudgetsRouteImport.update({
  id: '/budgets',
  path: '/budgets',
  getParentRoute: () => protectedRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/budgets': typeof protectedBudgetsRoute
  '/dashboard': typeof protectedDashboardRoute
  '/ledgers': typeof protectedLedgersRoute
  '/reports': typeof protectedReportsRoute
  '/settings': typeof protectedSettingsRoute
  '/sync': typeof protectedSyncRoute
  '/transactions': typeof protectedTransactionsRoute
  '/onboarding': typeof publicOnboardingRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/budgets': typeof protectedBudgetsRoute
  '/dashboard': typeof protectedDashboardRoute
  '/ledgers': typeof protectedLedgersRoute
  '/reports': typeof protectedReportsRoute
  '/settings': typeof protectedSettingsRoute
  '/sync': typeof protectedSyncRoute
  '/transactions': typeof protectedTransactionsRoute
  '/onboarding': typeof publicOnboardingRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/(protected)': typeof protectedRouteRouteWithChildren
  '/(public)': typeof publicRouteRouteWithChildren
  '/(protected)/budgets': typeof protectedBudgetsRoute
  '/(protected)/dashboard': typeof protectedDashboardRoute
  '/(protected)/ledgers': typeof protectedLedgersRoute
  '/(protected)/reports': typeof protectedReportsRoute
  '/(protected)/settings': typeof protectedSettingsRoute
  '/(protected)/sync': typeof protectedSyncRoute
  '/(protected)/transactions': typeof protectedTransactionsRoute
  '/(public)/onboarding': typeof publicOnboardingRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/budgets'
    | '/dashboard'
    | '/ledgers'
    | '/reports'
    | '/settings'
    | '/sync'
    | '/transactions'
    | '/onboarding'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/budgets'
    | '/dashboard'
    | '/ledgers'
    | '/reports'
    | '/settings'
    | '/sync'
    | '/transactions'
    | '/onboarding'
  id:
    | '__root__'
    | '/'
    | '/(protected)'
    | '/(public)'
    | '/(protected)/budgets'
    | '/(protected)/dashboard'
    | '/(protected)/ledgers'
    | '/(protected)/reports'
    | '/(protected)/settings'
    | '/(protected)/sync'
    | '/(protected)/transactions'
    | '/(public)/onboarding'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  protectedRouteRoute: typeof protectedRouteRouteWithChildren
  publicRouteRoute: typeof publicRouteRouteWithChildren
}

declare module '@tanstack/solid-router' {
  interface FileRoutesByPath {
    '/(public)': {
      id: '/(public)'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof publicRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(protected)': {
      id: '/(protected)'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof protectedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(public)/onboarding': {
      id: '/(public)/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof publicOnboardingRouteImport
      parentRoute: typeof publicRouteRoute
    }
    '/(protected)/transactions': {
      id: '/(protected)/transactions'
      path: '/transactions'
      fullPath: '/transactions'
      preLoaderRoute: typeof protectedTransactionsRouteImport
      parentRoute: typeof protectedRouteRoute
    }
    '/(protected)/sync': {
      id: '/(protected)/sync'
      path: '/sync'
      fullPath: '/sync'
      preLoaderRoute: typeof protectedSyncRouteImport
      parentRoute: typeof protectedRouteRoute
    }
    '/(protected)/settings': {
      id: '/(protected)/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof protectedSettingsRouteImport
      parentRoute: typeof protectedRouteRoute
    }
    '/(protected)/reports': {
      id: '/(protected)/reports'
      path: '/reports'
      fullPath: '/reports'
      preLoaderRoute: typeof protectedReportsRouteImport
      parentRoute: typeof protectedRouteRoute
    }
    '/(protected)/ledgers': {
      id: '/(protected)/ledgers'
      path: '/ledgers'
      fullPath: '/ledgers'
      preLoaderRoute: typeof protectedLedgersRouteImport
      parentRoute: typeof protectedRouteRoute
    }
    '/(protected)/dashboard': {
      id: '/(protected)/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof protectedDashboardRouteImport
      parentRoute: typeof protectedRouteRoute
    }
    '/(protected)/budgets': {
      id: '/(protected)/budgets'
      path: '/budgets'
      fullPath: '/budgets'
      preLoaderRoute: typeof protectedBudgetsRouteImport
      parentRoute: typeof protectedRouteRoute
    }
  }
}

interface protectedRouteRouteChildren {
  protectedBudgetsRoute: typeof protectedBudgetsRoute
  protectedDashboardRoute: typeof protectedDashboardRoute
  protectedLedgersRoute: typeof protectedLedgersRoute
  protectedReportsRoute: typeof protectedReportsRoute
  protectedSettingsRoute: typeof protectedSettingsRoute
  protectedSyncRoute: typeof protectedSyncRoute
  protectedTransactionsRoute: typeof protectedTransactionsRoute
}

const protectedRouteRouteChildren: protectedRouteRouteChildren = {
  protectedBudgetsRoute: protectedBudgetsRoute,
  protectedDashboardRoute: protectedDashboardRoute,
  protectedLedgersRoute: protectedLedgersRoute,
  protectedReportsRoute: protectedReportsRoute,
  protectedSettingsRoute: protectedSettingsRoute,
  protectedSyncRoute: protectedSyncRoute,
  protectedTransactionsRoute: protectedTransactionsRoute,
}

const protectedRouteRouteWithChildren = protectedRouteRoute._addFileChildren(
  protectedRouteRouteChildren,
)

interface publicRouteRouteChildren {
  publicOnboardingRoute: typeof publicOnboardingRoute
}

const publicRouteRouteChildren: publicRouteRouteChildren = {
  publicOnboardingRoute: publicOnboardingRoute,
}

const publicRouteRouteWithChildren = publicRouteRoute._addFileChildren(
  publicRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  protectedRouteRoute: protectedRouteRouteWithChildren,
  publicRouteRoute: publicRouteRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
