/// <reference lib="webworker" />
import { precacheAndRoute, cleanupOutdatedCaches } from "workbox-precaching";
import { clientsClaim } from "workbox-core";

declare let self: ServiceWorkerGlobalScope;

// Precache all assets generated by Vite
precacheAndRoute(self.__WB_MANIFEST);

cleanupOutdatedCaches();
self.skipWaiting();
clientsClaim();

// Background Sync functionality
self.addEventListener("sync", (event: any) => {
  if (event.tag === "sync-data") {
    console.log("[SW] Background sync triggered");
    event.waitUntil(
      self.clients.matchAll().then((clients) => {
        clients.forEach((client) => {
          client.postMessage({ type: "SYNC_TRIGGER" });
        });
      }),
    );
  }
});

// Listen for messages from the main app
self.addEventListener("message", async (event) => {
  if (event.data && event.data.type === "SKIP_WAITING") {
    await self.skipWaiting();
  }
});
